services:
  #
  # Twitter Stream Auth Configuration
  #
  twitter_stream_api:
    class: Mineur\TwitterStreamApi\PublicStream
    arguments:
      - '%consumer_key%'
      - '%consumer_secret%'
      - '%access_token%'
      - '%access_token_secret%'